-- Seed data for Bucharest geopoints
INSERT INTO geopoints (id, title, slug, lat, lng, description, created_at, updated_at, approved_at, approved_by) VALUES
('bucharest-1', 'Palace of the Parliament', 'palace-of-the-parliament', 44.4275, 26.0875, 'The world''s largest civilian building with an administrative function, built during the communist era. A massive architectural marvel with over 1,000 rooms.', datetime('now'), datetime('now'), datetime('now'), 'system'),
('bucharest-2', 'Old Town (Lipscani)', 'old-town-lipscani', 44.4319, 26.1033, 'The historic center of Bucharest with cobblestone streets, 19th-century buildings, restaurants, bars, and shops. The heart of the city''s nightlife.', datetime('now'), datetime('now'), datetime('now'), 'system'),
('bucharest-3', 'Herăstrău Park', 'herastrau-park', 44.4750, 26.0833, 'The largest park in Bucharest, featuring a beautiful lake, walking paths, the Village Museum, and numerous restaurants. Perfect for outdoor activities.', datetime('now'), datetime('now'), datetime('now'), 'system'),
('bucharest-4', 'Romanian Athenaeum', 'romanian-athenaeum', 44.4414, 26.0972, 'A stunning concert hall and landmark of Romanian culture, built in 1888. Home to the George Enescu Philharmonic Orchestra.', datetime('now'), datetime('now'), datetime('now'), 'system'),
('bucharest-5', 'Calea Victoriei', 'calea-victoriei', 44.4361, 26.1014, 'One of Bucharest''s most beautiful boulevards, lined with historic buildings, luxury shops, and cultural institutions. A must-walk street.', datetime('now'), datetime('now'), datetime('now'), 'system'),
('bucharest-6', 'Revolution Square', 'revolution-square', 44.4358, 26.1025, 'Historic square where the 1989 Romanian Revolution began. Features the Memorial of Rebirth and the former Communist Party headquarters.', datetime('now'), datetime('now'), datetime('now'), 'system'),
('bucharest-7', 'Bucharest Botanical Garden', 'bucharest-botanical-garden', 44.4367, 26.0583, 'A peaceful oasis in the city center with over 10,000 plant species, greenhouses, and beautiful walking paths.', datetime('now'), datetime('now'), datetime('now'), 'system'),
('bucharest-8', 'Stavropoleos Monastery', 'stavropoleos-monastery', 44.4317, 26.1025, 'A beautiful 18th-century Orthodox monastery with stunning architecture and a peaceful courtyard in the heart of the old city.', datetime('now'), datetime('now'), datetime('now'), 'system'),
('bucharest-9', 'Carol Park', 'carol-park', 44.4167, 26.1000, 'Historic park with the Mausoleum, beautiful gardens, and panoramic views of the city. A great spot for relaxation.', datetime('now'), datetime('now'), datetime('now'), 'system'),
('bucharest-10', 'Dimitrie Gusti National Village Museum', 'village-museum', 44.4733, 26.0725, 'An open-air museum showcasing traditional Romanian village life with authentic houses and buildings from different regions.', datetime('now'), datetime('now'), datetime('now'), 'system'); 